### PR TITLE
MO-115

### PR DESCRIPTION
**Pull request by saga95**
Closes: [MO-115](https://smashtaps.atlassian.net/browse/MO-115?atlOrigin=eyJpIjoiMDIzYWRhNjVmY2UzNGQzOWE0NGY2ZmY3ZDcyNTdiMWMiLCJwIjoiaiJ9)

- Add lamda function to getCompanyByCompanyHandler
- Tested with Postman
   - URL endpoint: https://wqofnuj4f8.execute-api.us-west-2.amazonaws.com/dev/companyHandler/sameerascompany-19he8kmu8lzv5
   
getCompanyByCompanyHandlerResults

### CODE REVIEW

**Review by octaneC8H18 — APPROVED** [review]
Looks good to me

**Review by octaneC8H18 — CHANGES_REQUESTED** [review]
Anyways data should be pulled from job table :)

**Comment by saga95** [comment]
Updated the table to Job table 

Results: 

byCompanyHandler- Results

**Review by octaneC8H18 — APPROVED** [review]
LGTM

**Pull request merged**
